### ISSUE TITLE
Bforartists not compiling.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3640]
We have a problem with a incomplete merge. Bforartists does not compile at the moment. There are vital differences between Blender and Bforartists. Some may be the few hours difference between the time @Draise14 made the merge, but this cannot be the cause since Bforartists does not compile.

![problem](https://github.com/Bforartists/Bforartists/assets/13919702/f8787acf-b2fe-400c-9b4b-13ab1066d441)

![vitaldiffs](https://github.com/Bforartists/Bforartists/assets/13919702/31a43ddb-c265-492e-8a8f-4d50ec601ff0)

**Comment by Draise14** [comment]
Ok, cleared my compiling solution. Seems that file was cached, and I can reproduce.

**Comment by ReinerBforartists** [comment]
Always start from scratch :)

**Comment by Draise14** [comment]
I did. So it was weird. I was compiling multiple times fixing each document. I'll try take a look today.

**Comment by ReinerBforartists** [comment]
Weird indeed. Since from scratch has no cache O_O

Good luck ^^

**Comment by Draise14** [comment]
hurrrrduuuuurr, I didn't push the working build in the `blender_sync_master`.

**Comment by Draise14** [comment]
@ReinerBforartists can you switch you branch and try build again?

**Comment by Draise14** [comment]
Slippery fingers.

![image](https://github.com/Bforartists/Bforartists/assets/35357409/b6431ac9-effc-4607-93cb-abc31977056f)

Here it is, my last commit did not include the new files.

**Comment by Draise14** [comment]
Test compiling now from another duplicate, so far the LITE build succeeded without problems.

**Comment by ReinerBforartists** [comment]
This can't fit. I had a cmake file open, with quite a few differences.

**Comment by Draise14** [comment]
Tested, release built successfully. Do a test build, let me know. I can no-longer reproduce the issue.

**Comment by ReinerBforartists** [comment]
Builds. But as told, i have spotted vital differences. Blender does for sure not go back from cc files to c files. See shot from the cmake file above.

**Comment by ReinerBforartists** [comment]
Yeah, as expected. It finishes building, but doesn't start then. Immediately closes. This was the Linux build so far.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5e1a2e49-1428-4953-88fd-f8318c84b759)

Windows is fine. 

Something is strange with how you are comparing, I can't see the C files Blender has, and I technically cleaned that up in the blender_sync_master. We all are both on the CC files now.  
![image](https://github.com/Bforartists/Bforartists/assets/35357409/cbe58dc7-dd5a-4d14-b7c7-df180b063d02)

**Comment by Draise14** [comment]
I tried compiling on Ubuntu, had a different issue, but also didn't update. I compared the cmake, some things in footer and header were different, but the document differences you had I couldn't find. 

Gonna have some lunch, then I'll review the files in that folder and commit to the sync branch again.

**Comment by Draise14** [comment]
To make this work again, do I do a meld check on everything of that folder? On everything?

**Comment by ReinerBforartists** [comment]
Well ... in the old days i would've started over with the merge. But yeah, a meld check between bfa and blender could also work.

**Comment by Draise14** [comment]
I did 5 compiles, Lite, Release, Debug. Then I erased the solution, did two more with Lite and Release. All succeeded. I then commit, then merged to master. Testing in Windows I assumed would work everywhere.. I guess OS tests have to be done too... 
Then you reported... 
Then I pushed again, pulled, then compiled from another cloned repo. Succeeded in both with both Lite and Release 
I then installed an Arch distro, got it compiling with both Blender and Bforartists, and also succeeded with a Lite release on both. I'll test a Release and base compile tomorrow. 

I'll go through the folder and compare tomorrow also, Saturday, to tidy anything up that I find with meld and also try get a clean compile on Ubuntu in the VM.

**Comment by ReinerBforartists** [comment]
Normally this is true. Usually one compile is enough to test if BFA compiles in general. There are problems that shows when you do a release build. But completely missing files is not part of it.

I still wonder which step you missed. When you start from scratch then there is no cache. And when there is no cache then you should've run into the problem immediately. And when you work as shown by me then you know the files that has thrown a merge conflict. Checking them again might've fixed it. I could swear that the cmake file was part of it. Every change from a c file to cc file is also a change at the corresponding cmake file.

Either way, the problem needs a fix. And this before we merge even more code in. To merge at this point makes no sense anymore. Well. we could revert to the state before the merge, and do the whole merge again with current code. But that's even more effort.

**Comment by ReinerBforartists** [comment]
Hmm, okay, windows compiles and starts flawless. Need to check a full build though, with cuda and optix.

Lemme have a quick look into the crash.log at Ubuntu. In case i find it. Why can't they give you the full path -.-

**Comment by ReinerBforartists** [comment]
I don't have the time or energy for this crap os anymore -.-

![crap](https://github.com/Bforartists/Bforartists/assets/13919702/1b02f9e2-3337-4761-b83f-9244166526c0)

**Comment by ReinerBforartists** [comment]
Very informative crashlog.txt -.-

![wtf](https://github.com/Bforartists/Bforartists/assets/13919702/c9aecfdb-9c1a-47cd-a749-bf327d3ba393)

**Comment by ReinerBforartists** [comment]
Python Backtrace is as close as i can get. End of road. No idea. And i don't have the time for further investigation at the moment, sorry. No Ubuntu devbuild anymore.

**Comment by ReinerBforartists** [comment]
Scripts folder is different. Did you forget to check the addons?

**Comment by ReinerBforartists** [comment]
Dunno if i am just lucky, or it is one of those changes that came in after the merge*, but the first quick test in source\blender\editors\space_view3d already revealed a code difference. 

*This is why i cannot do this fix here. This must be done by the one who did the merge.

Either way, please make a code comparison. This is too dangerous, even when it compiles. At least the submodules needs an update.

And then there is Ubuntu. You say it compiles and works just fine at Arch? Problem is, most Linux distros are based at Ubuntu. We cannot simply drop Ubuntu support. But i have no idea what the problem is with this crap os.

**Comment by ReinerBforartists** [comment]
This is what i mean with an unstable build. Tried to switch to Keybinding here to search for a hotkey ...

![windowscrash](https://github.com/Bforartists/Bforartists/assets/13919702/28d353cb-a2ac-4670-96b9-ce40ead81105)

**Comment by Draise14** [comment]
I really can't reproduce the bugs you're finding, now even on Ubuntu. 

![vmplayer_emgoGAGTLe](https://github.com/Bforartists/Bforartists/assets/35357409/b1546794-f9a4-4b4a-b357-fda4e91ca3af)

I have checked the files, and seems clean on my end. I did a new Ubuntu build environment, and it is compiling and running fine. I also tried to reproduce your issue here, but I can't. Checking on Blender from the day I did the merge, they indeed changed a toooone of documents even a few hours after I did my pull. Everything is going to *.CC with the merge I only had a fraction in *.CC. Which changes a lot of core code ever so slightly - so comparing to Blender now is very different - we would have to checkout and  compare on the exact hour I did it to be at ground zero. Anything at any other time will be off and possibly broken. So doing a partial code comparison will have to be to the date, to the hour - and I'm still not sure how to pull Blender at a specific time yet. I have already pulled the most recent from Blender which proves my case, more than another dozen documents need updates to the new file format they are implementing so a code comparison now is.. eh.. not gonna work, ei, I need to do a full merge.  

Base issue here is.. I did the merge on a Tuesday, since I didn't hear back from Iyad over the weekend and I had assumed he had started, which wasn't the case. 

So... 
- I cannot reproduce your compile bugs on Ubuntu, nor the instability.
- I can build `make` both on windows and ubuntu without issues. 
- I did a merge on a Tuesday
- I tried to reproduce your keymap issue a new compile on Ubuntu, Windows, and it's all working fine my end and I can't reproduce the instability
- I think maybe doing another merge will solve some of the migration issues Blender is doing in the core architecture and the de-phased documents I merged on Tuesday, then we can comb in stability.

**Comment by Draise14** [comment]
I also updated the addons folders. Are these the "submodules" that need folder comparison to check if they are good?

**Comment by ReinerBforartists** [comment]
> I have checked the files, and seems clean on my end. I did a new Ubuntu build environment, and it is compiling and running fine. I also tried to reproduce your issue here, but I can't. Checking on Blender from the day I did the merge, they indeed changed a toooone of documents even a few hours after I did my pull. Everything is going to *.CC with the merge I only had a fraction in *.CC. Which changes a lot of core code ever so slightly - so comparing to Blender now is very different - we would have to checkout and compare on the exact hour I did it to be at ground zero. Anything at any other time will be off and possibly broken. So doing a partial code comparison will have to be to the date, to the hour - and I'm still not sure how to pull Blender at a specific time yet. I have already pulled the most recent from Blender which proves my case, more than another dozen documents need updates to the new file format they are implementing so a code comparison now is.. eh.. not gonna work, ei, I need to do a full merge.

That's why i said you need to do this check. You have the Blender repo at the time at which you did the merge.

>I cannot reproduce your compile bugs on Ubuntu, nor the instability.

And the build that i can do simply crashes. I cannot do the devbuild anymore.

>I can build make both on windows and ubuntu without issues.

It compiles, but Ubuntu does not start, and Windows has crashes.

> I think maybe doing another merge will solve some of the migration issues Blender is doing in the core architecture and the de-phased documents I merged on Tuesday, then we can comb in stability.

This will solve nothing. We have the trouble code already onboard.

>I also updated the addons folders. Are these the "submodules" that need folder comparison to check if they are good?

Yes.

The folders that you need to compare is 

\locale
\scripts\addons
\scripts\addons_contrib
\tools

**Comment by Draise14** [comment]
So strange, I can launch, run BFA, and do it all on Ubuntu. 

I'll add those folders to my merge to-do list. I've compared addons and addon_contrib.

**Comment by ReinerBforartists** [comment]
Yes, odd indeed. The crash with Windows is easy to reproduce, and it was not switching to key binding, but typing in a letter in the edit box.

I did a debug now. But still struggle to understand what the problem is. I'll check if the trouble existed in an earlier devbuild. one moment ..

![trouble](https://github.com/Bforartists/Bforartists/assets/13919702/7c98c171-26cd-472f-b21e-c956b971e095)

![debug2](https://github.com/Bforartists/Bforartists/assets/13919702/bade006b-6daf-4259-82f2-72c917bff155)

**Comment by ReinerBforartists** [comment]
Possible troublemaker. And it's one of the cc files ...

You said you did a compare? :)

![troublemaker](https://github.com/Bforartists/Bforartists/assets/13919702/6db979e0-9153-4630-be1e-79305d7b421d)

**Comment by ReinerBforartists** [comment]
Okay, you got me. I will do the code comparison now. -.-

**Comment by iyadahmed** [comment]
how come non of this is happenning here?

**Comment by ReinerBforartists** [comment]
I have no idea. But i found some differences already. Fingers crossed that i have catched this baddie.

**Comment by ReinerBforartists** [comment]
Phew. This is muuuch better :D

It's not this much difference. Basically one overlooked file. And i am not sure if it was really the cause. Seems that my golden hand has simply catched the one and only bug in this merge.

I have while at it also updated a handful comments to the better.

On with the Ubuntu problem. Possible that i have to wait for the next merge here. Make Update, which i accidentally used here now, crawls for the newest libs. And they might be incompatible with the libs from the merge point. Maybe this is already the problem with the current Ubuntu build. But Draise said it worked for him. Hm.

I spotted that they have updated the blender themes again. The Blender dark theme is a bit of a problem, since Blender exports it as blank. We need to do a side by side comparison at one point i guess to get the Blender theme updated too.

![nowworking](https://github.com/Bforartists/Bforartists/assets/13919702/6c61ed16-68fe-4d5f-9b76-20e5d8630384)

**Comment by ReinerBforartists** [comment]
Ubuntu is still no go. It compiles fine, but quits at starting up already.

**Comment by iyadahmed** [comment]
> Ubuntu is still no go. It compiles fine, but quits at starting up already.

Btw I did the today's merge and all these issues disappeared ^^
can I push to master and see if issue disapperas instead of trying to fix ti manually? ^^

**Comment by ReinerBforartists** [comment]
Sure. Does this merge include my pushes?

**Comment by ReinerBforartists** [comment]
Compiling Blender at the moment. When Blender quits at startup too then i know that i have a problem with my Ubuntu installation.

**Comment by ReinerBforartists** [comment]
It's a Ubuntu problem. Blender craps out to the desktop at startup too.

![crappingout](https://github.com/Bforartists/Bforartists/assets/13919702/b7598494-055e-426e-9b9e-a98a43e933f0)

**Comment by ReinerBforartists** [comment]
_[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)_

So it is this one. Audiodriver realtime problem. Investigating.

**Comment by ReinerBforartists** [comment]
Okay, i have the suspicion that something has changed at the configuration of Blender regarding audio. Did a test on a old VM where BFA compiled fine before. And the same crash happens.

Will make it a own task now.

**Comment by ReinerBforartists** [comment]
Same on a completely fresh Ubuntu 22.04 VM. The one that i used to test if Ubuntu crashes with Cuda 12 ...

I think i will ask at Blender Developer now. Maybe somebody there knows what is going on.

**Comment by ReinerBforartists** [comment]
I think we can close this issue. The Ubuntu issue is separated, and the merge problems are fixed.

So closing.
