### ISSUE TITLE
Official Release - Bforartists 4.3.0

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4820]
Bforartists 4.3.0 is a polished version with new rainbow collections blocks, new geometry nodes for GP3, and lots of extra love everywhere thanks to everyone working so hard this trimester! Beautiful lovely work! I love this version. So.. Let's give it to the people. 

- [x] Update splashscreen + bump version
- [x] Fix high priority bugs/tasks (merge)
- [x] Create branch 
- [x] Create Release notes
- [ ] ~~Bump Documentation version, Branch and Compile documentation~~
- [ ] ~~Upload Documentation to Nextcloud~~
- [ ] ~~Do Documentation release on Github~~
- [x] Windows build
- [x] Windows Installer
- [x] Windows App Store
- [x] Linux Build
- [x] Linux Deb 
- [x] Linux Flatpak
- [x] Linux Appimage
- [x] Mac Universal Build
- [x] Mac Intel builds
- [x] Mac Silicon builds _(replaced by experimental universal build)_
- [x] Do release on Github
- [x] Do release on Website
- [x] Update release notes on website
- [ ] ~~Create publicity~~
- [x] Push

**Comment by Draise14** [comment]
Building windows now.

**Comment by Draise14** [comment]
middnight here on a Saturday, will try hit the release on Monday or Tuesday once we have the builds - and work documentation and release notes morrow and publicity Monday and tuesday

**Comment by Blenux** [comment]
done the linux builds and uploaded them, just having a issue with the intel version of macos (silicon one is done), will try again tomorrow.

**Comment by Blenux** [comment]
bah now its working omg, will have mac builds are after sleep

**Comment by ReinerBforartists** [comment]
Nice. Is there an universal build too?

**Comment by Blenux** [comment]
yeah can do on 3 versions if needed

**Comment by ReinerBforartists** [comment]
NEEED :D

**Comment by Blenux** [comment]
done Intel and Mac Silicon builds, will do the Universal one later

**Comment by Blenux** [comment]
mac universal done (uploading now)

**Comment by Draise14** [comment]
Pushed to website, current download links are to Nextcloud download links (direct) - will push to discord and socials once the website links are updated. 

Publicity.. coming later, got a plan, but my voice is still not recordable and I'm still zonked from the cold.

**Comment by Draise14** [comment]
Release notes have been updated too.

**Comment by ReinerBforartists** [comment]
Will upload to server now, update the links, and update the manual

**Comment by ReinerBforartists** [comment]
Ah, manual is still missing. Waiting ...

**Comment by Draise14** [comment]
Yep. Will do that today. Found some nice anticold meds. Slowly feeling better.

**Comment by Draise14** [comment]
ok, those meds really turned me into a zombie. I got hardly anything done today.

**Comment by ReinerBforartists** [comment]
Take care my friend. Nothing more important than health !

**Comment by Draise14** [comment]
Will take this weekend easy, then do documentation, then work 4.3.1 then publish publicity then.

**Comment by Blenux** [comment]
hope you are all good, just tag me when the branch is ready and will do the linux/mac builds again.

**Comment by Draise14** [comment]
Going to close, move publicity and documentation release for 4.3.1
